/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registro_tienda;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ESFOT
 */
public class Ventana extends javax.swing.JFrame {

    ArrayList <Fruta> listado_frutas = new ArrayList();
    ArrayList <Cliente> listado_clientes = new ArrayList(); 
    String codigo;
    String nombreFruta;
    String precio;
    String nombre;
    String cedula; 
    
    Fruta nueva = new Fruta("111", "Manzana", "25");
    Fruta nueva2 = new Fruta("222", "Pera", "55");
    Fruta nueva3 = new Fruta("333", "Uva", "20");
   
    Cliente nuevo = new Cliente(nombre, cedula); 
    
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTCliente = new javax.swing.JLabel();
        lblTFrutas = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        lblListaFrutas = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblNombreFruta = new javax.swing.JLabel();
        lblPrecioFruta = new javax.swing.JLabel();
        cbxFiltrador = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        lblTPedidos = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbxCedulas = new javax.swing.JComboBox<>();
        btnMostrarPedido = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        lblNombreClienteM = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblCedulaM = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPedidos = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        lblTotalM = new javax.swing.JLabel();
        lblCodigoM = new javax.swing.JLabel();
        lblNombreFrutaM = new javax.swing.JLabel();
        lblPrecioM = new javax.swing.JLabel();
        btnMostrarFruta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTCliente.setText("CLIENTE");

        lblTFrutas.setText("FRUTAS");

        lblNombreCliente.setText("Nombre");

        lblCedula.setText("Cédula");

        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });

        lblListaFrutas.setText("Lista de frutas");

        lblCodigo.setText("Código");

        lblNombreFruta.setText("Nombre");

        lblPrecioFruta.setText("Precio");

        cbxFiltrador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguna", "Manzana\t", "Pera", "Uva" }));

        btnRegistrar.setText("REGISTRAR PEDIDO");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblTPedidos.setText("PEDIDOS REGISTRADOS");

        jLabel10.setText("Lista de cédulas");

        jLabel11.setText("INFORMACIÓN DEL CLIENTE");

        btnMostrarPedido.setText("MOSTRAR PEDIDO");
        btnMostrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarPedidoActionPerformed(evt);
            }
        });

        jLabel12.setText("Nombre");

        lblNombreClienteM.setText(":");

        jLabel14.setText("Cédula");

        lblCedulaM.setText(":");

        jLabel16.setText("PEDIDOS DEL CLIENTE");

        txtPedidos.setColumns(20);
        txtPedidos.setRows(5);
        jScrollPane1.setViewportView(txtPedidos);

        jLabel17.setText("TOTAL");

        lblTotalM.setText(":");

        lblCodigoM.setText(":");

        lblNombreFrutaM.setText(":");

        lblPrecioM.setText(":");

        btnMostrarFruta.setText("Mostrar datos");
        btnMostrarFruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarFrutaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTFrutas)
                        .addGap(135, 135, 135))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(btnRegistrar))
                            .addComponent(lblTPedidos)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(cbxCedulas, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(btnMostrarPedido))
                            .addComponent(jLabel11))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblCedulaM, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblNombreClienteM, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblNombreCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblCedula)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCedula)))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblListaFrutas)
                                                .addComponent(lblCodigo))
                                            .addGap(18, 18, 18))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lblNombreFruta)
                                            .addGap(50, 50, 50)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPrecioFruta)
                                        .addGap(58, 58, 58)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxFiltrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCodigoM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(22, 22, 22))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblPrecioM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                        .addComponent(lblNombreFrutaM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(22, 22, 22)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMostrarFruta)
                        .addGap(0, 38, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTCliente)
                    .addComponent(lblTFrutas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreCliente)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCedula)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblListaFrutas)
                            .addComponent(cbxFiltrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMostrarFruta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigo)
                            .addComponent(lblCodigoM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreFruta)
                            .addComponent(lblNombreFrutaM, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrecioFruta)
                    .addComponent(lblPrecioM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTPedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbxCedulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarPedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lblNombreClienteM, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lblCedulaM)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblTotalM))
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed
 private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        String seleccion = cbxFiltrador.getSelectedItem().toString();
        if(txtNombreCliente.equals("") || txtCedula.equals("") || seleccion.equals("Ninguna") ){
        JOptionPane.showMessageDialog(rootPane, "Ingrese todos los datos !");
        }else{
            nombre= txtNombreCliente.getText(); 
            cedula= txtCedula.getText(); 
            nuevo= new Cliente (nombre, cedula); 
            listado_clientes.add(nuevo); 
            cbxCedulas.addItem(cedula);
            txtNombreCliente.setText("");
            txtCedula.setText("");
        }
        
 }
     private void btnMostrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        int cedulaSel = cbxCedulas.getSelectedIndex(); 
        if(cedulaSel ==0){
        
        
        }
       
        
        
        
        
    } 
    private void btnMostrarFrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarFrutaActionPerformed
        // TODO add your handling code here:
        int frutaSel= cbxFiltrador.getSelectedIndex();
           
        /*if(frutaSel==0){
             String codigo= nueva.getCodigo();
             String nombreFruta= nueva.getNombre();
             String precio= nueva.getPrecio();
            lblCodigoM.setText(codigo); 
            lblNombreFrutaM.setText(nombreFruta);
            lblPrecioM.setText(precio);          
    }//GEN-LAST:event_btnMostrarFrutaActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnMostrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarPedidoActionPerformed
      */
        if(frutaSel==0){
         lblCodigoM.setText(""); 
         lblNombreFrutaM.setText("");
         lblPrecioM.setText("");     
        }else if(frutaSel==1){
            codigo= nueva.getCodigo();
             nombreFruta= nueva.getNombre();
            precio= nueva.getPrecio();
            lblCodigoM.setText(codigo); 
            lblNombreFrutaM.setText(nombreFruta);
            lblPrecioM.setText(precio);          
    }else if(frutaSel==1){
             codigo= nueva2.getCodigo();
             nombreFruta= nueva2.getNombre();
            precio= nueva2.getPrecio();
            lblCodigoM.setText(codigo); 
            lblNombreFrutaM.setText(nombreFruta);
            lblPrecioM.setText(precio);    
    }else if(frutaSel==2){
            codigo= nueva3.getCodigo();
            nombreFruta= nueva3.getNombre();
            precio= nueva3.getPrecio();
            lblCodigoM.setText(codigo); 
            lblNombreFrutaM.setText(nombreFruta);
            lblPrecioM.setText(precio); 
    
    
    }
        
}    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarFruta;
    private javax.swing.JButton btnMostrarPedido;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbxCedulas;
    private javax.swing.JComboBox<String> cbxFiltrador;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCedulaM;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigoM;
    private javax.swing.JLabel lblListaFrutas;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNombreClienteM;
    private javax.swing.JLabel lblNombreFruta;
    private javax.swing.JLabel lblNombreFrutaM;
    private javax.swing.JLabel lblPrecioFruta;
    private javax.swing.JLabel lblPrecioM;
    private javax.swing.JLabel lblTCliente;
    private javax.swing.JLabel lblTFrutas;
    private javax.swing.JLabel lblTPedidos;
    private javax.swing.JLabel lblTotalM;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextArea txtPedidos;
    // End of variables declaration//GEN-END:variables
}
